### ISSUE TITLE
Compiling under R17 warns

### ISSUE THREAD

**Issue by davidoccam** [klajo/wpi#8]
==> wpi (compile)
/home/pi/rcouch-master/deps/wpi/src/wpi.erl:94: Warning: opaque type wpi_lcd_handle() is not exported
/home/pi/rcouch-master/deps/wpi/src/wpi.erl:99: Warning: opaque type wpi_serial_handle() is not exported

for information only

**Comment by klajo** [comment]
Thanks.  Fixed in 5b61c3a.
